import { toast } from "sonner"

/**
 * Utility function to trigger a native browser file download of a Blob.
 */
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.setAttribute("download", filename)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Mock utility exports for the Digital Marketing Simulation reports.
 * All functions return a Promise, simulate latency, and trigger a native download or toast.
 */

export async function exportToCSV(data: any[], filename: string): Promise<boolean> {
  return new Promise((resolve) => {
    toast.info(`Preparing CSV export: ${filename}...`)
    
    setTimeout(() => {
      try {
        // Simple CSV generation
        const headers = Object.keys(data[0] || {})
        const csvRows = [
          headers.join(","),
          ...data.map((row) =>
            headers
              .map((fieldName) => {
                const value = row[fieldName]
                const stringVal = typeof value === "object" ? JSON.stringify(value) : String(value)
                return `"${stringVal.replace(/"/g, '""')}"`
              })
              .join(",")
          ),
        ]
        const csvContent = csvRows.join("\n")
        const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
        
        downloadBlob(blob, filename.endsWith(".csv") ? filename : `${filename}.csv`)
        toast.success(`CSV Export complete: ${filename}`)
        resolve(true)
      } catch (error) {
        toast.error("Failed to generate CSV export")
        resolve(false)
      }
    }, 1200)
  })
}

export async function exportToJSON(data: any, filename: string): Promise<boolean> {
  return new Promise((resolve) => {
    toast.info(`Preparing JSON export: ${filename}...`)
    
    setTimeout(() => {
      try {
        const jsonContent = JSON.stringify(data, null, 2)
        const blob = new Blob([jsonContent], { type: "application/json;charset=utf-8;" })
        
        downloadBlob(blob, filename.endsWith(".json") ? filename : `${filename}.json`)
        toast.success(`JSON Export complete: ${filename}`)
        resolve(true)
      } catch (error) {
        toast.error("Failed to generate JSON export")
        resolve(false)
      }
    }, 800)
  })
}

export async function generatePDF(reportData: any): Promise<boolean> {
  return new Promise((resolve) => {
    const filename = `${reportData.name.toLowerCase().replace(/\s+/g, "-")}-export.pdf`
    toast.info(`Generating high-fidelity PDF layout for "${reportData.name}"...`)
    
    setTimeout(() => {
      try {
        // Generate a mock PDF summary content as a text file for demonstrating download action
        const timestamp = new Date().toLocaleString()
        const pdfContent = `
========================================================================
                 DIGITAL MARKETING SIMULATION PLATFORM
                        ANALYTICS REPORT EXPORT
========================================================================
Report Name:   ${reportData.name}
Report Type:   ${reportData.type.toUpperCase()}
Generated:     ${reportData.createdAt}
Export Date:   ${timestamp}
Filters:       ${JSON.stringify(reportData.filters, null, 2)}
Status:        READY

------------------------------------------------------------------------
                             EXECUTIVE SUMMARY
------------------------------------------------------------------------
This simulation report contains critical metrics regarding students,
cohort comparisons, organic SEO performance, and advertising campaigns.
The values reflect current round parameters and decisions logged.

For full visual charts, please print directly from the Report Viewer page.
------------------------------------------------------------------------
Generated by SimpLab Enterprise Analytics Engine.
========================================================================
`
        const blob = new Blob([pdfContent.trim()], { type: "text/plain;charset=utf-8;" })
        
        downloadBlob(blob, filename)
        toast.success(`PDF Document downloaded: ${filename}`)
        resolve(true)
      } catch (error) {
        toast.error("Failed to generate PDF document")
        resolve(false)
      }
    }, 2000)
  })
}

export async function generateExcel(data: any[], filename: string): Promise<boolean> {
  return new Promise((resolve) => {
    toast.info(`Structuring Excel spreadsheet: ${filename}...`)
    
    setTimeout(() => {
      try {
        // Create tab delimited content representing a basic mock Excel sheet
        const headers = Object.keys(data[0] || {})
        const sheetRows = [
          headers.join("\t"),
          ...data.map((row) =>
            headers
              .map((fieldName) => {
                const value = row[fieldName]
                return typeof value === "object" ? JSON.stringify(value) : String(value)
              })
              .join("\t")
          ),
        ]
        const sheetContent = sheetRows.join("\n")
        const blob = new Blob([sheetContent], { type: "application/vnd.ms-excel;charset=utf-8;" })
        
        downloadBlob(blob, filename.endsWith(".xls") ? filename : `${filename}.xls`)
        toast.success(`Excel Spreadsheet downloaded: ${filename}`)
        resolve(true)
      } catch (error) {
        toast.error("Failed to compile Excel file")
        resolve(false)
      }
    }, 1500)
  })
}
