-- AlterTable
ALTER TABLE "ScoreBreakdown" ADD COLUMN     "adaptability" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "budgetDiscipline" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "efficiencyRoi" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "riskManagement" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "strategicAlignment" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
